name: APIM policy tests

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

jobs:
  - job: Main
    pool:
      name: hmcts-agent-pool
      vmImage: ubuntu-16.04
    steps:
      - task: Bash@3
        displayName: Policy tests
        inputs:
          targetType: inline
          script: make test-ci
