name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

# Max 100 triggers per week per scheduler,
# hence the repeated declarations above.
schedules:
- cron: "*/5 9-17 * * 1"
  displayName: Run every 5 min on Mondays
  branches:
    include:
    - master
  always: true
- cron: "*/5 9-17 * * 2"
  displayName: Run every 5 min on Tuesdays
  branches:
    include:
    - master
  always: true
- cron: "*/5 9-17 * * 3"
  displayName: Run every 5 min on Wednesdays
  branches:
    include:
    - master
  always: true
- cron: "*/5 9-17 * * 4"
  displayName: Run every 5 min on Thursdays
  branches:
    include:
    - master
  always: true
- cron: "*/5 9-17 * * 5"
  displayName: Run every 5 min on Fridays
  branches:
    include:
    - master
  always: true

jobs:
  - job: ApimTests
    displayName: APIM tests
    workspace:
      clean: all
    pool:
      name: hmcts-agent-pool
      vmImage: ubuntu-16.04
    steps:
      - task: Bash@3
        displayName: Policy tests
        inputs:
          targetType: inline
          script: make test-ci
        env:
          SUBSCRIPTION_KEY: $(SUBSCRIPTION_KEY)
          SERVICE_SUBSCRIPTION: $(SERVICE_SUBSCRIPTION)
          CYPRESS_CASE_ID: $(CYPRESS_CASE_ID)
          CYPRESS_USERNAME: $(CYPRESS_USERNAME)
          CYPRESS_PASSWORD: $(CYPRESS_PASSWORD)
          PORTAL_EMAIL: $(PORTAL_EMAIL)
          PORTAL_PASSWORD: $(PORTAL_PASSWORD)
          PORTAL_BASE_URL: $(PORTAL_BASE_URL)
          PORTAL_PREVIEW_HOST: $(PORTAL_PREVIEW_HOST)
          PROXY_HOST: $(PROXY_HOST)
          PROXY_PORT: $(PROXY_PORT)

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          failTaskOnFailedTests: true
