name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

schedules:
- cron: "*/30 8-18 * * 1-5"
  displayName: Run every 30 min during weekdays hours
  branches:
    include:
    - master
  always: true

jobs:
  - job: Main
    workspace:
      clean: all
    pool:
      name: hmcts-agent-pool
      vmImage: ubuntu-16.04
    steps:
      - task: Bash@3
        displayName: Policy tests
        inputs:
          targetType: inline
          script: make test-ci
        env:
          SUBSCRIPTION_KEY: $(SUBSCRIPTION_KEY)
          SERVICE_SUBSCRIPTION: $(SERVICE_SUBSCRIPTION)
          CYPRESS_CASE_ID: $(CYPRESS_CASE_ID)
          CYPRESS_USERNAME: $(CYPRESS_USERNAME)
          CYPRESS_PASSWORD: $(CYPRESS_PASSWORD)
          PORTAL_EMAIL: $(PORTAL_EMAIL)
          PORTAL_PASSWORD: $(PORTAL_PASSWORD)
          PORTAL_BASE_URL: $(PORTAL_BASE_URL)
          PORTAL_PREVIEW_HOST: $(PORTAL_PREVIEW_HOST)
          PROXY_HOST: $(PROXY_HOST)
          PROXY_PORT: $(PROXY_PORT)

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          failTaskOnFailedTests: true
